export const  ALL_ANIMALS_REQUEST = 'ALL_ANIMALS_REQUEST'
export const  ALL_ANIMALS_SUCCESS = 'ALL_ANIMALS_SUCCESS'
export const  ALL_ANIMALS_FAIL = 'ALL_ANIMALS_FAIL'

export const  ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST'
export const  ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS'
export const  ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL'

export const  CLEAR_ERRORS = 'CLEAR_ERRORS'